<?php

namespace App\Base\Providers\Collective;

use Collective\Html\FormBuilder;
use Collective\Html\HtmlBuilder;
use Illuminate\Contracts\Routing\UrlGenerator;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;

class BaseFormBuilder extends FormBuilder
{
    public const SHOW_LOADING_ENABLE = 1;

    protected bool $hasValidateMsg = false;

    public function __construct(HtmlBuilder $html, UrlGenerator $url, Factory $view, $csrfToken, Request $request = null)
    {
        parent::__construct($html, $url, $view, $csrfToken, $request);
    }

    public function open(array $options = [])
    {
        $options['enctype'] = 'multipart/form-data';
        if (!isset($options['show-loading'])) {
            $options['show-loading'] = self::SHOW_LOADING_ENABLE;
        }

        return parent::open($options);
    }

    public function text($name, $value = null, $options = [])
    {
        if (!isset($options['show_error']) || !$options['show_error']) {
            $options['class'] = isset($options['class']) ? $options['class'] . ' show-error' : ' show-error';
        }

        return parent::text($name, $value, $options);
    }

    public function select($name, $list = [], $selected = null, array $selectAttributes = [], array $optionsAttributes = [], array $optgroupsAttributes = [])
    {
        if (!isset($selectAttributes['show_error']) || !$selectAttributes['show_error']) {
            $selectAttributes['class'] = isset($selectAttributes['class']) ? $selectAttributes['class'] . ' show-error' : ' show-error';
        }

        return parent::select($name, $list, $selected, $selectAttributes, $optionsAttributes, $optgroupsAttributes); // TODO: Change the autogenerated stub
    }

    public function upload($name, $options = [])
    {
        // show error message
        $input = '<div class="show-error-message"></div>';

        $this->setPreviewFile($name, $input, $options);

        // set message validate file upload
        $this->setValidateFileMsg($input);

        // options
        $options['class'] = data_get($options, 'class', 'input-file');
        $options['id'] = 'uploadFile-' . $name;
        $options['data-label'] = $options['data-label'] ?? $name;
        $options['ext'] = implode(',', $options['ext'] ?? []);
        $options['size'] = implode(',', $options['size'] ?? []);

        // input file
        $inputFile = $this->input('file', $name, null, $options);

        return $inputFile . $input;
    }

    protected function setPreviewFile($name, &$input, $options)
    {
        $fileType = data_get($options, 'type', 'image');
        $fileUploaded = data_get($options, 'file-uploaded');
        $showRemoveType = data_get($options, 'show_remove_type');
        $previewUrl = data_get($options, 'preview-url');
        $input .= '<div id="preview-file-' . $name . '" class="mt-2 preview-file ' . ('image' == $fileType ? 'preview-image ' : '') . '">';

        if (empty($previewUrl)) {
            $input .= '</div>';

            return;
        }

        if ('image' == $fileType) {
            $input .= '<img class="' . data_get($options, 'preview-image-class') . '" src="' . $previewUrl . '">';
        } else {
            $input .= data_get($options, 'file_name');
        }

        if ($showRemoveType && $fileUploaded) {
            if ('button' === $showRemoveType) {
                $input .= '<button type="button" class="btn btn-danger remove-file">削除</button>';
            } elseif ('icon' === $showRemoveType) {
                $input .= '<i class="remove-file la la-close"></i>';
            }

            $input .= '<input class="file-uploaded" type="hidden" value="' . $fileUploaded . '" name="' . $name . '">';
        }

        $input .= '</div>';
    }

    protected function setValidateFileMsg(&$input)
    {
        if ($this->hasValidateMsg) {
            return;
        }

        $validateMsg = Lang::get('validation');

        $msg = [
            'min' => $validateMsg['min']['file'],
            'max' => $validateMsg['max']['file'],
            'mimes' => $validateMsg['mimes'],
        ];

        $input .= '<script> var validateFileMsg = ' . json_encode($msg) . '</script>';
        $this->hasValidateMsg = true;
    }
}
