name: Checking code
description: Checking code using static analysis tools
runs:
  using: composite
  steps:
    - name: Install Laravel Pint
      shell: bash
      run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
    - name: Check code with Pint
      shell: bash
      run: ./vendor/bin/pint --config config/pint.json -v
